### ISSUE TITLE
Reference Subsections and Repeats

### ISSUE THREAD

**Issue by hampusnasstrom** [hampusnasstrom/metainfo-yaml2py#10]
The following YAML file crashes in multiple places:
```yaml
definitions:
  name: 'ELN for MBE SiGe'
  sections:  # Schemas consist of section definitions
    MbeExperiment:
      base_sections: 
       - ../upload/raw/base_classes.schema.archive.yaml#Experiment 
      m_annotations:
        eln: 
          hide: ['end_time', 'lab_id', 'location']
        template:
          PublicationReference: {}
          SubstratePreparation: {}
          SubstrateCutting: {}
          GrowthRecipe: {}
          GrowthLog: {}
      sub_sections:
        PublicationReference:
          repeats: true
          m_annotations:
            eln:
          section: nomad.datamodel.metainfo.eln.PublicationReference
        SubstratePreparation:
          section:
            base_sections: 
            - '#/SubstratePreparation'
        SubstrateCutting:
          section:
            #############################base_sections:
            ##############################################################################################- nomad.datamodel.metainfo.eln.SampleCut
            # m_annotations:
            #   eln: 
            #     properties:
            #       order: ["datetime", "name", "inputs", "number_of_samples", "outputs", "lab_id", "users", "description"]
            quantities:
              method:
                type: str 
                default: "Substrate Cutting"
        GrowthRecipe:
          section:
            base_sections: 
            - '#/GrowthRecipe'
        CalibrationDateSources:
          section:
            base_sections: 
            - '#/CalibrationDateSources'
        GrowthLog:
          section:
            base_sections: 
            - '#/GrowthLog'
        AFMmeasurements:
          section:
            base_sections: 
            - nomad.parsing.tabular.TableData 
            m_annotations:
              eln: 
            quantities:
              data_file:
                type: str
                default: '#data/data_file'
                description: |
                  A reference to an uploaded .xlsx
                m_annotations:
                  tabular_parser:
                    comment: '#'
                    mode: row
                    target_sub_section: 
                    - tasks
                  browser:
                    adaptor: RawFileAdaptor 
                  eln:
                    component: FileEditQuantity
            sub_sections:
              tasks:
                repeats: true
                section:
                  base_sections: 
                  - '#/AFMmeasurement'
    AFMmeasurement:
      base_sections: 
        - nomad.datamodel.metainfo.eln.Measurement
        - nomad.parsing.tabular.TableData 
      m_annotations:
        eln: 
          # hide: ['name']
      quantities:
        method:
          type: str 
          default: "AFM"
    SubstratePreparation:
      base_sections: 
        - nomad.datamodel.metainfo.eln.Activity
      m_annotations:
        eln:
      quantities:
        method:
          type: str 
          default: "Substrate Preparation"
      sub_sections:
        steps:
          repeats: True
          section:  
            m_annotations:
              eln: 
                properties:
                  order: ["duration", "ratio", "step_number"]
            quantities:
              step_number:
                type: int
                description: sequential number of the step on going
                m_annotations:
                  eln:
                    component: NumberEditQuantity
              ratio:
                type: str
                m_annotations:
                  eln:
                    component: StringEditQuantity
              duration:
                type: np.float64
                unit: second
                description: Duration of the current step in seconds
                m_annotations:
                  eln:
                    component: NumberEditQuantity
                    defaultDisplayUnit: second
    GrowthRecipe:
      base_sections: 
        - nomad.datamodel.metainfo.eln.Activity
        - nomad.datamodel.metainfo.eln.ikz_mbe.GrowthRecipe
      m_annotations:
        eln:
    GrowthLog:
      base_sections: 
        - nomad.datamodel.metainfo.eln.Activity
        - nomad.datamodel.metainfo.eln.ikz_mbe.GrowthLog
      m_annotations:
        eln:
    CalibrationDateSources:
      base_sections: 
        - nomad.datamodel.metainfo.eln.Activity
      m_annotations:
        eln:
      quantities:
        source_material:
          type: str
          description: FILL THE DESCRIPTION
          m_annotations:
            eln:
              component: StringEditQuantity
        calibration_date:
          type: Datetime
          description: FILL THE DESCRIPTION
          m_annotations:
            eln:
              component: DateTimeEditQuantity
```
