### ISSUE TITLE
Deal With Annotations Generally

### ISSUE THREAD

**Issue by hampusnasstrom** [hampusnasstrom/metainfo-yaml2py#7]
Deal with annotations according to:
```yaml
definitions:
  sections:
    MyAnnotatedSection:
      m_annotations:
        annotation_name:
          key1: value
          key2: value
```
into
```python
a_annotation_name = {
  "key1": "value",
  "key1": "value",
}
```
